    //object of all prophets
    //each prophet an object containing, name, birthdate, deathdate, sustaindate, order, photos, videos, audios, mantra, trivias
    var prophets = [
        {   name: 'Joseph Smith, Jr.',
            photo: [
                'joseph-smith.jpg',
                'JS_Bible_st.jpg'], 
            birthdate:'December 23, 1805',
            deathdate:'June 27, 1844',
            sustaindate:'April 6, 1830',
            ordinal:'1st',
            conference:'"The King Follett Sermon", April 1840'},
            
        {   name: 'Brigham Young',
            photo: [
                'BY_mm7_st.jpg',            
                'BY_mm3_st.jpg'],
            birthdate:'June 1, 1801',
            deathdate:'August 29, 1877',
            sustaindate:'December 27, 1847',
            ordinal:'2nd',
            conference:'This is the work of God, April 1877'},
            
        {   name: 'John Taylor',
            photo: [
                'JT_mm3_st.jpg',
                'JT_mm4_st.jpg'],
            birthdate:'November 1, 1808',
            deathdate:'July 25, 1887',
            sustaindate:'October 10, 1880',
            ordinal:'3rd',
            conference:'We Will Trust in The Living God, October 1884'},
            
        {   name: 'Wilford Woodruff',
            photo: [
                'WW_mm10_st.jpg',
                'WW_mm7_st.jpg'],
            birthdate:'March 1, 1807 ',
            deathdate:'September 2, 1898',
            sustaindate:'April 7, 1889',
            ordinal:'4th',
            conference:'Rise Up and Bear Off This Kingdom, April 1898'},
            
        {   name: 'Lorenzo Snow',
            photo: [
                'LS_mm2_st.jpg',
                'LS_mm4_st.jpg'],
            birthdate:'April 3, 1814',
            deathdate:'October 10, 1901',
            sustaindate:'September 13, 1898',
            ordinal:'5th',
            conference:'The Channel of the Priesthood, October 1901'},
            
        {   name: 'Joseph F. Smith',
            photo: [
                'JFS_mm2_st.jpg',
                'JFS_mm5_st.jpg'],
            birthdate:'November 13, 1838',
            deathdate:' November 19, 1918',
            sustaindate:'October 17, 1901',
            ordinal:'6th',
            conference:'Continuous Communication With the Spirit of the Lord , October 1918'},
            
        {   name: 'Heber J. Grant',
            photo: [
                'HJG_mm11_st.jpg',
                'HJG_mm2_st.jpg'],
            birthdate:'November 22, 1856',
            deathdate:'May 14, 1945',
            sustaindate:'November 23, 1918',
            ordinal:'7th',
            conference:'Joy in the Integrity of the Officers of the Church, April 1945'},
            
        {   name: 'George Albert Smith',
            photo: [
                'GAS_mm1_st.jpg',
                'GAS_mm9_st.jpg'],
            birthdate:'April 4, 1870',
            deathdate:'April 4, 1951',
            sustaindate:'May 21, 1945',
            ordinal:'8th',
            conference:'Divine Mission of Jesus Christ, October 1950'},
            
        {   name: 'David O. McKay',
            photo: [
                'DOM_mm2_st.jpg',
                'DOM_mm5_st.jpg'],
            birthdate:'September 8, 1873',
            deathdate:'January 18, 1970',
            sustaindate:'April 9, 1951',
            ordinal:'9th',
            conference:'How may we know Him? October 1966'},
            
        {   name: 'Joseph Fielding Smith',
            photo: [
                'JFiS_Pres-apr-23-1970_st.jpg',
                'JFiSmith_1923_st.jpg'],
            birthdate:'July 19, 1876',
            deathdate:'July 2, 1972',
            sustaindate:'January 23, 1970',
            ordinal:'10th',
            conference:'Believe in Chris, April 1972'},
            
        {   name: 'Harold B. Lee',
            photo: [
                'HBL_standing-by-globe_st.jpg',
                'HBL_1936_p6581_1_st.jpg'],
            birthdate:'March 28, 1899',
            deathdate:'December 26, 1973',
            sustaindate:'July 7, 1972',
            ordinal:'11th',
            conference:'Where else can you go for guidance? October 1973'},
            
        {   name: 'Spencer W. Kimball',
            photo: [
                'SWK-2_st.jpg',
                'SWK_ca-1950-60_st.jpg'],
            birthdate:'March 28, 1895',
            deathdate:'November 5, 1985',
            sustaindate:'December 30, 1973',
            ordinal:'12th',
            conference:'The Mission of the Church is Threefold, April 1981'},
            
        {   name: 'Ezra Taft Benson',
            photo: [
                'ETB_Ezra-T-Benson_st.jpg',
                'ETB_p5216_9_710_st.jpg'],
            birthdate:'August 4, 1899',
            deathdate:'May 30, 1994',
            sustaindate:'November 10, 1985',
            ordinal:'13th',
            conference:'Each Of You Truly Is A Child Of God, April 1989'},
            
        {   name: 'Howard W. Hunter',
            photo: [
                'HWH-21_st.jpg',
                'HWH-20_st.jpg'],
            birthdate:'November 14, 1907',
            deathdate:'March 3, 1995',
            sustaindate:'June 5, 1994',
            ordinal:'14th',
            conference:'As Followers of Jesus Christ, October 1994'},
            
        {   name: 'Gordon B. Hinckley',
            photo: [
                'GBH-Hinckley2_st.jpg',
                'GBH-portrait_1959_st.jpg'],
            birthdate:'June 23, 1910',
            deathdate:'January 27, 2008',
            sustaindate:'March 12, 1995',
            ordinal:'15th',
            conference:'The Lord Fulfills His Ppromise, October 2007'},
            
        {   name: 'Thomas S. Monson',
            photo: [
                'thomas-s-monson-large.jpg',
                'Thomas-S-Monson-1963.jpg'],
            birthdate: 'August 21, 1927',
            deathdate: 'present',
            sustaindate: 'February 3, 2008',
            ordinal:'16th',
            conference:'Obedience Brings Blessings, April 2013'}
    ];
    //object of all apostles
    //each apostle an object conaining: name, birthdate, sustaindate, position, photos, videos, audios, mantra, trivias
    //http://www.maxoutput.com/djdj/apostles_answers.html
    var apostles = [
        {   name: 'Thomas S. Monson',
            position: 'President',
            photo: [
                'thomas-s-monson-large.jpg',
                'Thomas-S-Monson-1937.jpg',
                'conference/thomas-s-monson.jpg'],
            mantra: 'Rescue',
            birthdate: 'August 21, 1927',
            sustaindate: 'October 4, 1963',
            ordinal:'1st',
            mission: 'Mission President, Canadian Mission, Ontario, 1959-1962',
            birthplace: 'Salt Lake City, Utah',
            profession: '',
            conference:'Obedience Brings Blessings' },
            
        {   name: 'Henry B. Eyring',
            position: 'First Counselor, First Presidency',
            photo: [
                'henry-b-eyring-large.jpg',
                'Henry_B_Eyring2.jpg',
                'conference/henry-b-eyring.jpg'],
            mantra: '',
            birthdate: 'May 31, 1933',
            sustaindate: 'April 1, 1995',
            ordinal:'10th',
            mission: '',
            birthplace: 'Princeton, New Jersey',
            profession: '',
            conference:'"Come unto Me"' },
            
        {   name: 'Dieter F. Uchtdorf ',
            position: 'Second Counselor, First Presidency',
            photo: [
                'dieter-f-uchtdorf-large.jpg',
                'dieter-uctdorf-german-air-force.jpg',
                'conference/dieter-f-uchtdorf.jpg'],
            mantra: '',
            birthdate: 'November 6, 1940',
            sustaindate: 'October 2, 2004',
            ordinal:'11th',
            mission: '',
            birthplace: 'Ostrava, Czechoslovakia',
            profession: '',
            conference:"The Hope of God's Light" },
            
        {   name: 'Boyd K. Packer',
            position: 'President, Quorum of the Twelve Apostles',
            photo: [
                'boyd-k-packer-large.jpg',
                'packer-bio-world-war-two.jpg',
                'conference/boyd-k-packer.jpg'],
            mantra: '',
            birthdate: 'September 10, 1924',
            sustaindate: 'April 9, 1970',
            ordinal:'2nd',
            mission: '',
            birthplace: 'Brigham City, Utah',
            profession: '',
            conference:'These Things I Know' },
            
        {   name: 'L. Tom Perry',
            photo: [
                'l-tom-perry-large.jpg',
                'l-tom-perry-marines.jpg',
                'conference/l-tom-perry.jpg'],
            mantra: '',
            birthdate: 'August 5, 1922',
            sustaindate: 'April 6, 1974',
            ordinal:'3rd',
            mission: '',
            birthplace: 'Logan, Cache, Utah',
            profession: '',
            conference:'Obedience to Law Is Liberty' },
            
        {   name: 'Russell M. Nelson',
            photo: [
                'russell-m-nelson-large.jpg',
                'russell-nelson-army.jpg',
                'conference/russell-m-nelson.jpg'],
            mantra: '',
            birthdate: 'September 9, 1924',
            sustaindate: 'April 7, 1984',
            ordinal:'4th',
            mission: '',
            birthplace: 'Salt Lake City, Utah',
            profession: '',
            conference:'Catch the Wave' },
            
        {   name: 'Dallin H. Oaks',
            photo: [
                'dallin-h-oaks-large.jpg',
                'dallin-h-oaks.jpg',
                'conference/dallin-h-oaks.jpg'],
            mantra: '',
            birthdate: 'August 12, 1932',
            sustaindate: 'May 3, 1984',
            ordinal:'5th',
            mission: '',
            birthplace: 'Provo, Utah',
            profession: '',
            conference:'Followers of Christ' },
            
        {   name: 'M. Russell Ballard',
            photo: [
                'm-russell-ballard-large.jpg',
                'russell-ballard-boy.jpg',
                'conference/m-russell-ballard.jpg'],
            mantra: '',
            birthdate: 'October 8, 1928',
            sustaindate: 'October 10, 1985',
            ordinal:'6th',
            mission: '',
            birthplace: 'Salt Lake City, Utah',
            profession: '',
            conference:'"This Is My Work and Glory"' },
            
        {   name: 'Richard G. Scott',
            photo: [
                'richard-g-scott-large.jpg',
                'richard-g-scott-navy.jpg',
                'conference/richard-g-scott.jpg'],
            mantra: '',
            birthdate: 'November 7, 1928',
            sustaindate: 'October 1, 1988',
            ordinal:'7th',
            mission: '',
            birthplace: 'Pocatello, Idaho',
            profession: '',
            conference:'For Peace at Home' },
            
        {   name: 'Robert D. Hales',
            photo: [
                'robert-d-hales-large.jpg',
                'robert-hales-boy.jpg',
                'conference/robert-d-hales.jpg'],
            mantra: '',
            birthdate: 'August 24, 1932',
            sustaindate: 'April 2, 1994',
            ordinal:'8th',
            mission: '',
            birthplace: 'New York City, New York',
            profession: '',
            conference:'Stand Strong in Holy Places' },
            
        {   name: 'Jeffrey R. Holland',
            photo: [
                'jeffrey-r-holland-large.jpg',
                'jeffery-r-holland-young.jpg',
                'conference/jeffrey-r-holland.jpg'],
            mantra: '',
            birthdate: 'December 3, 1940',
            sustaindate: 'June 23, 1994',
            ordinal:'9th',
            mission: '',
            birthplace: 'St George, Utah',
            profession: '',
            conference:'"Lord, I Believe"' },
            
        {   name: 'David A. Bednar',
            photo: [
                'david-a-bednar-large.jpg',
                'david-bednar-boy.jpg',
                'conference/david-a-bednar.jpg'],
            mantra: '',
            birthdate: 'June 15, 1952',
            sustaindate: 'October 2, 2004',
            ordinal:'12th',
            mission: '',
            birthplace: 'San Leandro, California',
            profession: '',
            conference:'We Believe in Being Chaste' },
            
        {   name: 'Quentin L. Cook',
            photo: [
                'quentin-l-cook-large.jpg',
                'quentin-cook-boy.jpg',
                'conference/quentin-l-cook.jpg'],
            mantra: '',
            birthdate: 'September 8, 1940',
            sustaindate: 'October 6, 2007',
            ordinal:'13th',
            mission: '',
            birthplace: 'Logan, Utah',
            profession: '',
            conference:'Personal Peace: The Reward of Righteousness' },
            
        {   name: 'D. Todd Christofferson',
            photo: [
                'd-todd-christofferson-large.jpg',
                'todd-christofferson-boy.jpg',
                'conference/d-todd-christofferson.jpg'],
            mantra: '',
            birthdate: 'January 24, 1945',
            sustaindate: 'April 5, 2008',
            ordinal:'14th',
            mission: '',
            birthplace: 'Pleasant Grove, Utah',
            profession: '',
            conference:'Redemption' },
            
        {   name: 'Neil L. Andersen',
            photo: [
                'neil-l-andersen-large.jpg',
                'neil-l-andersen-missionary.jpg',
                'conference/neil-l-andersen.jpg'],
            mantra: '',
            birthdate: 'August 9, 1951',
            sustaindate: 'April 4, 2009',
            ordinal:'15th',
            mission: '',
            birthplace: 'Logan, Utah',
            profession: '',
            conference: "It's a Miracle" }
    ];