var current_leaders = [
	{
		'name': 'Thomas S. Monson',
		'first_name': 'Thomas',
		'middle_name': 'Spencer',
		'last_name': 'Monson',
		'initial': 'middle_name',
		'position': 'President',
		'birthdate': 'August 21, 1927',
		'ordained_date': 'October 4, 1963',
		'ordinal': '1st',
		'order': 1,
		'deathdate': null,
		'hometown': 'Salt Lake City, Utah',
		'img': 'thomas-s-monson-large.jpg',
		'img_young': 'Thomas-S-Monson-1937.jpg',
		'conference_talks': '218',
		'profession': 'Businessman, Printing & Publishing Industry',
		'military': 'Ensign, United States Navy',
		'education': 'University of Utah (B.S.), Brigham Young University (M.B.A.)',
		'mission': null,
		'reason_called': 'Death of Henry D. Moyle',
	},
	{
		'name': 'Henry B. Eyring',
		'first_name': 'Henry',
		'middle_name': 'Bennion',
		'last_name': 'Eyring',
		'initial': 'middle_name',
		'position': 'First Counselor, First Presidency',
		'birthdate': 'May 31, 1933',
		'ordained_date': 'April 1, 1995',
		'ordinal': '10th',
		'order': 10,
		'deathdate': null,
		'hometown': 'Princeton, New Jersey',
		'img': 'henry-b-eyring-large.jpg',
		'img_young': 'Henry_B_Eyring2.jpg',
		'conference_talks': '67',
		'profession': 'Professor, Education Administration (President of Ricks)',
		'military': 'US Air Force',
		'education': 'University of Utah (B.S.), Harvard University (M.B.A., D.B.A.)',
		'mission': null,
		'reason_called': 'Death of Howard W. Hunter',
	},
	{
		'name': 'Dieter F. Uchtdorf',
		'first_name': 'Dieter',
		'middle_name': 'Friedrich',
		'last_name': 'Uchtdorf',
		'initial': 'middle_name',
		'position': 'Second Counselor, First Presidency',
		'birthdate': 'November 6, 1940',
		'ordained_date': 'October 2, 2004',
		'ordinal': '11th',
		'order': 11,
		'deathdate': null,
		'hometown': 'Nazi-occupied Protectorate of Bohemia and Moravia (now Ostrava, Czech Republic)',
		'img': 'dieter-f-uchtdorf-large.jpg',
		'img_young': 'dieter-uctdorf-german-air-force.jpg',
		'conference_talks': '45',
		'profession': 'Pilot',
		'military': 'Fighter Pilot, West German Air Force',
		'education': 'International Institute for Management Development',
		'mission': null,
		'reason_called': 'Deaths of David B. Haight and Neal A. Maxwell',
	},
	{
		'name': 'Boyd K. Packer',
		'first_name': 'Boyd',
		'middle_name': 'Kenneth',
		'last_name': 'Packer',
		'initial': 'middle_name',
		'position': 'President, Quorum of the Twelve Apostles',
		'birthdate': 'September 10, 1924',
		'ordained_date': 'April 9, 1970',
		'ordinal': '2nd',
		'order': 2,
		'deathdate': null,
		'hometown': 'Brigham City, Utah',
		'img': 'boyd-k-packer-large.jpg',
		'img_young': 'packer-bio-world-war-two.jpg',
		'conference_talks': '105',
		'profession': 'Educator, Education Administration',
		'military': 'Pilot, US Air Force',
		'education': 'Utah State University (B.S., M.S.), Brigham Young University (Ed.D.)',
		'mission': null,
		'reason_called': 'Death of David O. McKay',
	},
	{
		'name': 'L. Tom Perry',
		'first_name': 'Lowell',
		'middle_name': 'Tom',
		'last_name': 'Perry',
		'initial': 'first_name',
		'position': 'Apostle',
		'birthdate': 'August 5, 1922',
		'ordained_date': 'April 6, 1974',
		'ordinal': '3rd',
		'order': 3,
		'deathdate': null,
		'hometown': 'Logan, Utah',
		'img': 'l-tom-perry-large.jpg',
		'img_young': 'l-tom-perry-marines.jpg',
		'conference_talks': '86',
		'profession': 'Businessman, Retail',
		'military': 'US Marine Corps',
		'education': 'Utah State University (B.S.)',
		'mission': 'Northern States Mission',
		'reason_called': 'Death of Harold B. Lee',
	},
	{
		'name': 'Russell M. Nelson',
		'first_name': 'Russell',
		'middle_name': 'Marion',
		'last_name': 'Nelson',
		'initial': 'middle_name',
		'position': 'Apostle',
		'birthdate': 'September 9, 1924',
		'ordained_date': 'April 7, 1984',
		'ordinal': '4th',
		'order': 4,
		'deathdate': null,
		'hometown': 'Salt Lake City, Utah',
		'img': 'russell-m-nelson-large.jpg',
		'img_young': 'russell-nelson-army.jpg',
		'conference_talks': '65',
		'profession': 'Heart Surgeon',
		'military': 'Captain, Army Medical Corps, US Army',
		'education': 'University of Utah (B.A., M.D.), University of Minnesota (Ph.D)',
		'mission': null,
		'reason_called': 'Deaths of LeGrand Richards and Mark E. Petersen',
	},
	{
		'name': 'Dallin H. Oaks',
		'first_name': 'Dallin',
		'middle_name': 'Harris',
		'last_name': 'Oaks',
		'initial': 'middle_name',
		'position': 'Apostle',
		'birthdate': 'August 12, 1932',
		'ordained_date': 'May 3, 1984',
		'ordinal': '5th',
		'order': 5,
		'deathdate': null,
		'hometown': 'Provo, Utah',
		'img': 'dallin-h-oaks-large.jpg',
		'img_young': 'dallin-h-oaks.jpg',
		'conference_talks': '63',
		'profession': 'Lawyer, Judge',
		'military': 'US National Guard',
		'education': 'Brigham Young University (B.S.), University of Chicago Law School (J.D.)',
		'mission': null,
		'reason_called': 'Deaths of LeGrand Richards and Mark E. Petersen',
	},
	{
		'name': 'M. Russell Ballard',
		'first_name': 'Melvin',
		'middle_name': 'Russell',
		'last_name': 'Ballard',
		'initial': 'first_name',
		'position': 'Apostle',
		'birthdate': 'October 8, 1928',
		'ordained_date': 'October 10, 1985',
		'ordinal': '6th',
		'order': 6,
		'deathdate': null,
		'hometown': 'Salt Lake City, Utah',
		'img': 'm-russell-ballard-large.jpg',
		'img_young': 'russell-ballard-boy.jpg',
		'conference_talks': '70',
		'profession': 'Businessman',
		'military': 'First Lieutenant, US Army Reserve',
		'education': 'University of Utah',
		'mission': 'England',
		'reason_called': 'Death of Bruce R. McConkie',
	},
	{
		'name': 'Richard G. Scott',
		'first_name': 'Richard',
		'middle_name': 'Gordon',
		'last_name': 'Scott',
		'initial': 'middle_name',
		'position': 'Apostle',
		'birthdate': 'November 7, 1928',
		'ordained_date': 'October 1, 1988',
		'ordinal': '7th',
		'order': 7,
		'deathdate': null,
		'hometown': 'Pocatello, Idaho',
		'img': 'richard-g-scott-large.jpg',
		'img_young': 'richard-g-scott-navy.jpg',
		'conference_talks': '59',
		'profession': 'Nuclear Engineer',
		'military': null,
		'education': 'George Washington University (B.S.)',
		'mission': 'Uruguay Montevideo Mission',
		'reason_called': 'Death of Marion G. Romney',
	},
	{
		'name': 'Robert D. Hales',
		'first_name': 'Robert',
		'middle_name': 'Dean',
		'last_name': 'Hales',
		'initial': 'middle_name',
		'position': 'Apostle',
		'birthdate': 'August 24, 1932',
		'ordained_date': 'April 2, 1994',
		'ordinal': '8th',
		'order': 8,
		'deathdate': null,
		'hometown': 'New York City, New York',
		'img': 'robert-d-hales-large.jpg',
		'img_young': 'robert-hales-boy.jpg',
		'conference_talks': '53',
		'profession': 'Businessman',
		'military': 'Captain, US Air Force',
		'education': 'University of Utah (B.S.), Harvard Business School (MBA)',
		'mission': null,
		'reason_called': 'Death of Marvin J. Ashton',
	},
	{
		'name': 'Jeffrey R. Holland',
		'first_name': 'Jeffrey',
		'middle_name': 'Roy',
		'last_name': 'Holland',
		'initial': 'middle_name',
		'position': 'Apostle',
		'birthdate': 'December 3, 1940',
		'ordained_date': 'June 23, 1994',
		'ordinal': '9th',
		'order': 9,
		'deathdate': null,
		'hometown': 'St George, Utah',
		'img': 'jeffrey-r-holland-large.jpg',
		'img_young': 'jeffery-r-holland-young.jpg',
		'conference_talks': '44',
		'profession': 'Teacher, Education Administration (Institute Director, Dean and School President)',
		'military': null,
		'education': 'Brigham Young University (B.A., M.A.), Yale University (M.A., Ph.D.)',
		'mission': 'England',
		'reason_called': 'Death of Ezra Taft Benson',
	},
	{
		'name': 'David A. Bednar',
		'first_name': 'David',
		'middle_name': 'Allan',
		'last_name': 'Bednar',
		'initial': 'middle_name',
		'position': 'Apostle',
		'birthdate': 'June 15, 1952',
		'ordained_date': 'October 2, 2004',
		'ordinal': '12th',
		'order': 12,
		'deathdate': null,
		'hometown': 'San Leandro, California',
		'img': 'david-a-bednar-large.jpg',
		'img_young': 'david-bednar-boy.jpg',
		'conference_talks': '21',
		'profession': 'Professor, Education Administration (President of Ricks)',
		'military': null,
		'education': 'Brigham Young University (B.S., M.S.), Purdue University (Ph.D.)',
		'mission': 'Germany',
		'reason_called': 'Deaths of David B. Haight and Neal A. Maxwell',
	},
	{
		'name': 'Quentin L. Cook',
		'first_name': 'Quentin',
		'middle_name': 'LaMar',
		'last_name': 'Cook',
		'initial': 'middle_name',
		'position': 'Apostle',
		'birthdate': 'September 8, 1940',
		'ordained_date': 'October 6, 2007',
		'ordinal': '13th',
		'order': 13,
		'deathdate': null,
		'hometown': 'Logan, Utah',
		'img': 'quentin-l-cook-large.jpg',
		'img_young': 'quentin-cook-boy.jpg',
		'conference_talks': '17',
		'profession': 'Attorney',
		'military': null,
		'education': 'Utah State University (B.S.), Stanford Law School (J.D.)',
		'mission': 'England',
		'reason_called': 'Death of James E. Faust',
	},
	{
		'name': 'D. Todd Christofferson',
		'first_name': 'David',
		'middle_name': 'Todd',
		'last_name': 'Christofferson',
		'initial': 'first_name',
		'position': 'Apostle',
		'birthdate': 'January 24, 1945',
		'ordained_date': 'April 5, 2008',
		'ordinal': '14th',
		'order': 14,
		'deathdate': null,
		'hometown': 'Pleasant Grove, Utah',
		'img': 'd-todd-christofferson-large.jpg',
		'img_young': 'todd-christofferson-boy.jpg',
		'conference_talks': '20',
		'profession': 'Lawyer',
		'military': null,
		'education': 'Brigham Young University, Duke Law School (J.D.)',
		'mission': 'Argentina',
		'reason_called': 'Death of Gordon B. Hinckley',
	},
	{
		'name': 'Neil L. Andersen',
		'first_name': 'Neil',
		'middle_name': 'Linden',
		'last_name': 'Andersen',
		'initial': 'middle_name',
		'position': 'Apostle',
		'birthdate': 'August 9, 1951',
		'ordained_date': 'April 4, 2009',
		'ordinal': '15th',
		'order': 15,
		'deathdate': null,
		'hometown': 'Logan, Utah',
		'img': 'neil-l-andersen-large.jpg',
		'img_young': 'neil-l-andersen-missionary.jpg',
		'conference_talks': '17',
		'profession': 'Businessman',
		'military': null,
		'education': 'Brigham Young University, Harvard Business School (MBA)',
		'mission': 'France',
		'reason_called': 'Death of Joseph B. Wirthlin',
	},
];

var latter_day_prophets = [
	{
		'name': 'Thomas S. Monson',
		'first_name': 'Thomas',
		'middle_name': 'Spencer',
		'last_name': 'Monson',
		'initial': 'middle_name',
		'position': 'President',
		'birthdate': 'August 21, 1927',
		'president_date': 'February 3, 2008',
		'ordained_date': 'October 10, 1963',
		'ordinal': '16th',
		'order': 16,
		'deathdate': null,
		'hometown': 'Salt Lake City, Utah',
		'img': 'thomas-s-monson-large.jpg',
		'img_young': 'Thomas-S-Monson-1937.jpg',
		'conference_talks': '218',
		'profession': 'Businessman, Printing & Publishing Industry',
		'military': 'Ensign, United States Navy',
		'education': 'University of Utah, MBA, Brigham Young University',
		'mission': null,
		'reason_called': 'Death of Henry D. Moyle; N. Eldon Tanner added to First Presidency',
	},
	{
		'name': 'Gordon B. Hinckley',
		'first_name': 'Gordon',
		'middle_name': 'Bitner',
		'last_name': 'Hinckley',
		'initial': 'middle_name',
		'position': 'President',
		'birthdate': 'June 23, 1910',
		'president_date': 'March 12, 1995',
		'ordained_date': 'October 5, 1961',
		'deathdate': 'January 27, 2008',
		'ordinal': '15th',
		'order': 15,
		'hometown': 'Salt Lake City, Utah',
		'img': 'GBH-Hinckley2_st.jpg',
		'img_young': 'GBH-portrait_1959_st.jpg',
		'conference_talks': '237',
		'profession': 'Journalist, Executive Secretary',
		'military': null,
		'education': 'University of Utah (B.A.)',
		'mission': 'Britain',
		'reason_called': 'Hugh B. Brown added to First Presidency',
	},
	{
		'name': 'Howard W. Hunter',
		'first_name': 'Howard',
		'middle_name': 'William',
		'last_name': 'Hunter',
		'initial': 'middle_name',
		'position': 'President',
		'birthdate': 'November 14, 1907',
		'president_date': 'June 5, 1994',
		'ordained_date': 'October 15, 1959',
		'deathdate': 'March 3, 1995',
		'ordinal': '14th',
		'order': 14,
		'hometown': 'Boise, Idaho',
		'img': 'HWH-21_st.jpg',
		'img_young': 'HWH-20_st.jpg',
		'conference_talks': '73',
		'profession': 'Lawyer',
		'military': null,
		'education': 'Southwestern Law School',
		'mission': null,
		'reason_called': 'Death of Stephen L Richards and addition of Henry D. Moyle to First Presidency',
	},
	{
		'name': 'Ezra Taft Benson',
		'first_name': 'Ezra',
		'middle_name': 'Taft',
		'last_name': 'Benson',
		'initial': null,
		'position': 'President',
		'birthdate': 'August 4, 1899',
		'president_date': 'November 10, 1985',
		'ordained_date': 'October 7, 1943',
		'deathdate': 'May 30, 1994',
		'ordinal': '13th',
		'order': 13,
		'hometown': 'Whitney, Idaho',
		'img': 'ETB_Ezra-T-Benson_st.jpg',
		'img_young': 'ETB_p5216_9_710_st.jpg',
		'conference_talks': '111',
		'profession': 'Agriculture, US Secretary of Agriculture',
		'military': null,
		'education': 'Utah State University, Brigham Young University, Iowa State University',
		'mission': 'Britain',
		'reason_called': 'Deaths of Sylvester Q. Cannon and Rudger Clawson',
	},
	{
		'name': 'Spencer W. Kimball',
		'first_name': 'Spencer',
		'middle_name': 'Woolley',
		'last_name': 'Kimball',
		'initial': 'middle_name',
		'position': 'President',
		'birthdate': 'March 28, 1895',
		'president_date': 'December 30, 1973',
		'ordained_date': 'October 7, 1943',
		'deathdate': 'November 5, 1985',
		'ordinal': '12th',
		'order': 12,
		'hometown': 'Salt Lake City, Utah',
		'img': 'SWK-2_st.jpg',
		'img_young': 'SWK_ca-1950-60_st.jpg',
		'conference_talks': '121',
		'profession': 'Bank Cashier, Clerk, Finance',
		'military': 'Drafted in the Army, but never called for duty',
		'education': null,
		'mission': 'Central States Mission (called to Swiss-German Mission, but reassigned at the outbreak of WWI)',
		'reason_called': 'Deaths of Sylvester Q. Cannon and Rudger Clawson',
	},
	{
		'name': 'Harold B. Lee',
		'first_name': 'Harold',
		'middle_name': 'Bingham',
		'last_name': 'Lee',
		'initial': 'middle_name',
		'position': 'President',
		'birthdate': 'March 28, 1899',
		'president_date': 'July 7, 1972',
		'ordained_date': 'April 10, 1941',
		'deathdate': 'December 26, 1973',
		'ordinal': '11th',
		'order': 11,
		'hometown': 'Clifton, Idaho',
		'img': 'HBL_standing-by-globe_st.jpg',
		'img_young': 'HBL_1936_p6581_1_st.jpg',
		'conference_talks': '76',
		'profession': 'Teacher',
		'military': null,
		'education': 'Albion State Normal School',
		'mission': 'Western States',
		'reason_called': 'Death of Reed Smoot',
	},
	{
		'name': 'Joseph Fielding Smith',
		'first_name': 'Joseph',
		'middle_name': 'Fielding',
		'last_name': 'Smith',
		'initial': null,
		'position': 'President',
		'birthdate': 'July 19, 1876',
		'president_date': 'January 23, 1970',
		'ordained_date': 'April 7, 1910',
		'deathdate': 'July 2, 1972',
		'ordinal': '10th',
		'order': 10,
		'hometown': 'Salt Lake City, Utah',
		'img': 'JFiS_Pres-apr-23-1970_st.jpg',
		'img_young': 'JFiSmith_1923_st.jpg',
		'conference_talks': '122',
		'profession': 'Church Historian and Recorder',
		'military': null,
		'education': 'Latter-day Saint College',
		'mission': 'Great Britain',
		'reason_called': 'John Henry Smith added to First Presidency',
	},
	{
		'name': 'David O. McKay',
		'first_name': 'David',
		'middle_name': 'Oman',
		'last_name': 'McKay',
		'initial': 'middle_name',
		'position': 'President',
		'birthdate': 'September 8, 1873',
		'president_date': 'April 9, 1951',
		'ordained_date': 'April 9, 1906',
		'deathdate': 'January 18, 1970',
		'ordinal': '9th',
		'order': 9,
		'hometown': 'Huntsville, Alabama',
		'img': 'DOM_mm2_st.jpg',
		'img_young': 'DOM_mm5_st.jpg',
		'conference_talks': '388',
		'profession': 'Teacher and Education Administrator',
		'military': null,
		'education': 'University of Utah',
		'mission': 'Great Britain',
		'reason_called': 'Resignation of Matthias F. Cowley and John W. Taylor from the Quorum of the Twelve; death of Marriner W. Merrill',
	},
	{
		'name': 'George Albert Smith',
		'first_name': 'George',
		'middle_name': 'Albert',
		'last_name': 'Smith',
		'initial': 'middle_name',
		'position': 'President',
		'birthdate': 'April 4, 1870',
		'president_date': 'May 21, 1945',
		'ordained_date': 'October 8, 1903',
		'deathdate': 'April 4, 1951',
		'ordinal': '8th',
		'order': 8,
		'hometown': 'Salt Lake City, Utah',
		'img': 'GAS_mm1_st.jpg',
		'img_young': 'GAS_mm9_st.jpg',
		'conference_talks': '115',
		'profession': null,
		'military': null,
		'education': 'University of Utah',
		'mission': 'Southern States',
		'reason_called': 'Death of Brigham Young, Jr.',
	},
	{
		'name': 'Heber J. Grant',
		'first_name': 'Heber',
		'middle_name': 'Jeddy',
		'last_name': 'Grant',
		'initial': 'middle_name',
		'position': 'President',
		'birthdate': 'November 22, 1856',
		'president_date': 'November 23, 1918',
		'ordained_date': 'October 16, 1882',
		'deathdate': 'May 14, 1945',
		'ordinal': '7th',
		'order': 7,
		'hometown': 'Salt Lake City, Utah',
		'img': 'HJG_mm11_st.jpg',
		'img_young': 'HJG_mm2_st.jpg',
		'conference_talks': '233',
		'profession': 'Businessman',
		'military': null,
		'education': null,
		'mission': null,
		'reason_called': 'Death of Orson Pratt',
	},
	{
		'name': 'Joseph F. Smith',
		'first_name': 'Joseph',
		'middle_name': 'Fielding',
		'last_name': 'Smith',
		'initial': 'middle_name',
		'position': 'President',
		'birthdate': 'November 13, 1838',
		'president_date': 'October 17, 1901',
		'ordained_date': 'July 1, 1866',
		'deathdate': 'November 19, 1918',
		'ordinal': '6th',
		'order': 6,
		'hometown': 'Far West, Missouri',
		'img': 'JFS_mm2_st.jpg',
		'img_young': 'JFS_mm5_st.jpg',
		'conference_talks': '173',
		'profession': 'Church Historian Clerk, Utah territorial House of Representatives',
		'military': 'Nauvoo Legion, Utah Territory',
		'education': null,
		'mission': 'Sandwich Islands (Hawaiian Islands), Great Britain, Sandwich Islands',
		'reason_called': 'Brigham Young\'s discretion',
	},
	{
		'name': 'Lorenzo Snow',
		'first_name': 'Lorenzo',
		'middle_name': null,
		'last_name': 'Snow',
		'initial': null,
		'position': 'President',
		'birthdate': 'April 3, 1814',
		'president_date': 'September 13, 1898',
		'ordained_date': 'February 12, 1849',
		'deathdate': 'October 10, 1901',
		'ordinal': '5th',
		'order': 5,
		'hometown': 'Mantua, Ohio',
		'img': 'LS_mm2_st.jpg',
		'img_young': 'LS_mm4_st.jpg',
		'conference_talks': '53',
		'profession': 'Teacher',
		'military': null,
		'education': 'Oberlin College',
		'mission': 'Ohio, Illinois & Kentucky, England, Italy & Switzerland, Sandwich Islands',
		'reason_called': 'Excommunication of Lyman Wight',
	},
	{
		'name': 'Wilford Woodruff',
		'first_name': 'Wilford',
		'middle_name': null,
		'last_name': 'Woodruff',
		'initial': null,
		'position': 'President',
		'birthdate': 'March 1, 1807',
		'president_date': 'April 7, 1889',
		'ordained_date': 'April 26, 1839',
		'deathdate': 'September 2, 1898',
		'ordinal': '4th',
		'order': 4,
		'hometown': 'Farmington, Connecticut',
		'img': 'WW_mm10_st.jpg',
		'img_young': 'WW_mm7_st.jpg',
		'conference_talks': '133',
		'profession': 'Farmer & Stockman',
		'military': 'Chaplain, Nauvoo Legion',
		'education': null,
		'mission': 'Arkansas, Tennessee & Kentucky, New England, England, Eastern States',
		'reason_called': 'Replenishing Quorum of the Twelve',
	},
	{
		'name': 'John Taylor',
		'first_name': 'John',
		'middle_name': null,
		'last_name': 'Taylor',
		'initial': null,
		'position': 'President',
		'birthdate': 'November 1, 1808',
		'president_date': 'October 10, 1880',
		'ordained_date': 'December 19, 1838',
		'deathdate': 'July 25, 1887',
		'ordinal': '3rd',
		'order': 3,
		'hometown': 'Milnthorpe, England',
		'img': 'JT_mm3_st.jpg',
		'img_young': 'JT_mm4_st.jpg',
		'conference_talks': '161',
		'profession': 'Cooper, Woodturner & Cabinetmaker',
		'military': null,
		'education': null,
		'mission': 'Britain, France, Eastern States',
		'reason_called': 'Replenishing Quorum of the Twelve',
	},
	{
		'name': 'Brigham Young',
		'first_name': 'Brigham',
		'middle_name': null,
		'last_name': 'Young',
		'initial': null,
		'position': 'President',
		'birthdate': 'June 1, 1801',
		'president_date': 'August 29, 1877',
		'ordained_date': 'February 14, 1835',
		'deathdate': 'December 27, 1847',
		'ordinal': '2nd',
		'order': 2,
		'hometown': 'Whitingham, Vermont',
		'img': 'BY_mm7_st.jpg',
		'img_young': 'BY_mm3_st.jpg',
		'conference_talks': '400',
		'profession': 'Carpenter, Blacksmith, Governor',
		'military': null,
		'education': null,
		'mission': 'Upper Canada',
		'reason_called': 'Initial organization of Quorum of the Twelve',
	},
	{
		'name': 'Joseph Smith, Jr',
		'first_name': 'Joseph',
		'middle_name': null,
		'last_name': 'Smith',
		'initial': null,
		'position': 'President',
		'birthdate': 'December 23, 1805',
		'president_date': 'April 6, 1830',
		'ordained_date': 'April 6, 1830',
		'deathdate': 'June 27, 1844',
		'ordinal': '1st',
		'order': 1,
		'hometown': 'Sharon, Vermont',
		'img': 'joseph-smith.jpg',
		'img_young': 'JS_Bible_st.jpg',
		'conference_talks': 'unknown',
		'profession': 'Farmer, Mayor',
		'military': 'Lieutenant General, Nauvoo Legion',
		'education': null,
		'mission': null,
		'reason_called': 'Organization of the Church',
	},
];