var living_general_authorities = [
/*//
	{
		'name': 'NAME',
		'first_name': 'FIRSTNAME',
		'middle_name': 'MIDDLENAME',
		'last_name': 'LASTNAME',
		'initial': 'middle_name',
		'position': null,
		'birthdate': 'BIRTHDATE',
		'ordained_date': 'ORDAINED_DATE',
		'ordinal': 'NUMBER',
		'deathdate': null,
		'hometown': 'HOMETOWN',
		'img': 'portrait.jpg',
		'img_young': 'img2.jpg',
		'conference_talks': '',
	},
//*/
	{
		'name': 'Thomas S. Monson',
		'first_name': 'Thomas',
		'middle_name': 'Spencer',
		'last_name': 'Monson',
		'initial': 'middle_name',
		'position': 'President',
		'birthdate': 'August 21, 1927',
		'ordained_date': 'October 4, 1963',
		'ordinal': '1st',
		'deathdate': null,
		'hometown': 'Salt Lake City, Utah',
		'img': 'thomas-s-monson-large.jpg',
		'img_young': 'Thomas-S-Monson-1937.jpg',
		'conference_talks': '220',
	},
	{
		'name': 'Henry B. Eyring',
		'first_name': 'Henry',
		'middle_name': 'Bennion',
		'last_name': 'Eyring',
		'initial': 'middle_name',
		'position': 'First Counselor, First Presidency',
		'birthdate': 'May 31, 1933',
		'ordained_date': 'April 1, 1995',
		'ordinal': '10th',
		'deathdate': null,
		'hometown': 'Princeton, New Jersey',
		'img': 'henry-b-eyring-large.jpg',
		'img_young': 'Henry_B_Eyring2.jpg',
		'conference_talks': '70',
	},
	{
		'name': 'Dieter F. Uchtdorf',
		'first_name': 'Dieter',
		'middle_name': 'Friedrich',
		'last_name': 'Uchtdorf',
		'initial': 'middle_name',
		'position': 'Second Counselor, First Presidency',
		'birthdate': 'November 6, 1940',
		'ordained_date': 'October 2, 2004',
		'ordinal': '11th',
		'deathdate': null,
		'hometown': 'Ostrava, Czechoslovakia',
		'img': 'dieter-f-uchtdorf-large.jpg',
		'img_young': 'dieter-uctdorf-german-air-force.jpg',
		'conference_talks': '',
	},
	{
		'name': 'Boyd K. Packer',
		'first_name': 'Boyd',
		'middle_name': 'Kenneth',
		'last_name': 'Packer',
		'initial': 'middle_name',
		'position': 'President, Quorum of the Twelve Apostles',
		'birthdate': 'September 10, 1924',
		'ordained_date': 'April 9, 1970',
		'ordinal': '2nd',
		'deathdate': null,
		'hometown': 'Brigham City, Utah',
		'img': 'boyd-k-packer-large.jpg',
		'img_young': 'packer-bio-world-war-two.jpg',
		'conference_talks': '',
	},
	{
		'name': 'L. Tom Perry',
		'first_name': 'Lowell',
		'middle_name': 'Tom',
		'last_name': 'Perry',
		'initial': 'first_name',
		'position': null,
		'birthdate': 'August 5, 1922',
		'ordained_date': 'April 6, 1974',
		'ordinal': '3rd',
		'deathdate': null,
		'hometown': 'Logan, Cache, Utah',
		'img': 'l-tom-perry-large.jpg',
		'img_young': 'l-tom-perry-marines.jpg',
		'conference_talks': '',
	},
	{
		'name': 'Russell M. Nelson',
		'first_name': 'Russell',
		'middle_name': 'Marion',
		'last_name': 'Nelson',
		'initial': 'middle_name',
		'position': null,
		'birthdate': 'September 9, 1924',
		'ordained_date': 'April 7, 1984',
		'ordinal': '4th',
		'deathdate': null,
		'hometown': 'Salt Lake City, Utah',
		'img': 'russell-m-nelson-large.jpg',
		'img_young': 'russell-nelson-army.jpg',
		'conference_talks': '',
	},
	{
		'name': 'Dallin H. Oaks',
		'first_name': 'Dallin',
		'middle_name': 'Harris',
		'last_name': 'Oaks',
		'initial': 'middle_name',
		'position': null,
		'birthdate': 'August 12, 1932',
		'ordained_date': 'May 3, 1984',
		'ordinal': '5th',
		'deathdate': null,
		'hometown': 'Provo, Utah',
		'img': 'dallin-h-oaks-large.jpg',
		'img_young': 'dallin-h-oaks.jpg',
		'conference_talks': '',
	},
	{
		'name': 'M. Russell Ballard',
		'first_name': 'Melvin',
		'middle_name': 'Russell',
		'last_name': 'Ballard',
		'initial': 'first_name',
		'position': null,
		'birthdate': 'October 8, 1928',
		'ordained_date': 'October 10, 1985',
		'ordinal': '6th',
		'deathdate': null,
		'hometown': 'Salt Lake City, Utah',
		'img': 'm-russell-ballard-large.jpg',
		'img_young': 'russell-ballard-boy.jpg',
		'conference_talks': '',
	},
	{
		'name': 'Richard G. Scott',
		'first_name': 'Richard',
		'middle_name': 'Gordon',
		'last_name': 'Scott',
		'initial': 'middle_name',
		'position': null,
		'birthdate': 'November 7, 1928',
		'ordained_date': 'October 1, 1988',
		'ordinal': '7th',
		'deathdate': null,
		'hometown': 'Pocatello, Idaho',
		'img': 'richard-g-scott-large.jpg',
		'img_young': 'richard-g-scott-navy.jpg',
		'conference_talks': '',
	},
	{
		'name': 'Robert D. Hales',
		'first_name': 'Robert',
		'middle_name': 'Dean',
		'last_name': 'Hales',
		'initial': 'middle_name',
		'position': null,
		'birthdate': 'August 24, 1932',
		'ordained_date': 'April 2, 1994',
		'ordinal': '8th',
		'deathdate': null,
		'hometown': 'New York City, New York',
		'img': 'robert-d-hales-large.jpg',
		'img_young': 'robert-hales-boy.jpg',
		'conference_talks': '',
	},
	{
		'name': 'Jeffrey R. Holland',
		'first_name': 'Jeffrey',
		'middle_name': 'Roy',
		'last_name': 'Holland',
		'initial': 'middle_name',
		'position': null,
		'birthdate': 'December 3, 1940',
		'ordained_date': 'June 23, 1994',
		'ordinal': '9th',
		'deathdate': null,
		'hometown': 'St George, Utah',
		'img': 'jeffrey-r-holland-large.jpg',
		'img_young': 'jeffery-r-holland-young.jpg',
		'conference_talks': '',
	},
	{
		'name': 'David A. Bednar',
		'first_name': 'David',
		'middle_name': 'Allan',
		'last_name': 'Bednar',
		'initial': 'middle_name',
		'position': null,
		'birthdate': 'June 15, 1952',
		'ordained_date': 'October 2, 2004',
		'ordinal': '12th',
		'deathdate': null,
		'hometown': 'San Leandro, California',
		'img': 'david-a-bednar-large.jpg',
		'img_young': 'david-bednar-boy.jpg',
		'conference_talks': '',
	},
	{
		'name': 'Quentin L. Cook',
		'first_name': 'Quentin',
		'middle_name': 'LaMar',
		'last_name': 'Cook',
		'initial': 'middle_name',
		'position': null,
		'birthdate': 'September 8, 1940',
		'ordained_date': 'October 6, 2007',
		'ordinal': '13th',
		'deathdate': null,
		'hometown': 'Logan, Utah',
		'img': 'quentin-l-cook-large.jpg',
		'img_young': 'quentin-cook-boy.jpg',
		'conference_talks': '',
	},
	{
		'name': 'D. Todd Christofferson',
		'first_name': 'David',
		'middle_name': 'Todd',
		'last_name': 'Christofferson',
		'initial': 'first_name',
		'position': null,
		'birthdate': 'January 24, 1945',
		'ordained_date': 'April 5, 2008',
		'ordinal': '14th',
		'deathdate': null,
		'hometown': 'Pleasant Grove, Utah',
		'img': 'd-todd-christofferson-large.jpg',
		'img_young': 'todd-christofferson-boy.jpg',
		'conference_talks': '',
	},
	{
		'name': 'Neil L. Andersen',
		'first_name': 'Neil',
		'middle_name': 'Linden',
		'last_name': 'Andersen',
		'initial': 'middle_name',
		'position': null,
		'birthdate': 'August 9, 1951',
		'ordained_date': 'April 4, 2009',
		'ordinal': '15th',
		'deathdate': null,
		'hometown': 'Logan, Utah',
		'img': 'neil-l-andersen-large.jpg',
		'img_young': 'neil-l-andersen-missionary.jpg',
		'conference_talks': '',
	},
];